services:
  app:
    container_name: "ticket_online"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/
    ports:
      - "6100:80"
    restart: always
    networks:
     - database_mysql_network


networks:
  database_mysql_network:
   ipam:
     config:
       - subnet: 192.168.12.0/24
