services:
  app:
    container_name: 'ticket_online_backend'
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/
    ports:
      - "8000:80"
    restart: always
    networks:
     - database_mysql_network

networks:
  database_mysql_network:
      external: true
